# Perfil ativo padrão
spring.profiles.active=default

# ---------------------------
# H2 In-Memory Database
# ---------------------------

spring.datasource.url=jdbc:h2:mem:banco
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Reduzir o log
logging.level.root=INFO

# Configuração da porta do servidor
server.port=8080
